In [1]:
import TorchESN as TN
import numpy as np
TN.torch_ESN([0.01,0.1,0.001])

Test error: 4.2772928769551166e-07


4.2772928769551166e-07

In [ ]:
%pdb
TN.torch_ESN([1.2,1.2,0.01])

Automatic pdb calling has been turned ON


NameError: name 'TN' is not defined

> <ipython-input-40-6582153be182>(2)<module>()
      1 get_ipython().run_line_magic('pdb', '')
----> 2 TN.torch_ESN([1.2,1.2,0.01])



In [1]:
import numpy as np

In [8]:
%pdb
N=5
p=np.random.randn(3,N)
fitnesss=np.linspace(10,1,10)
gbest_score=100
OldBest=gbest_score
for i in range(N):
    fitness=fitnesss[i]
    if gbest_score > fitness and OldBest>fitness:
            OldBest=gbest_score
            gbest_score = fitness
            print(p[:,i])
            gbest = p[:,i]
            
gbest

Automatic pdb calling has been turned OFF
[ 1.26416755 -0.73574689 -1.39063087]
[-0.25934764 -1.15957282  0.4386994 ]
[0.52191048 0.01901149 0.57199411]
[-0.08394607 -0.72685988  1.4308488 ]
[ 1.30033596  1.66431166 -1.07171452]


array([ 1.30033596,  1.66431166, -1.07171452])

In [6]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])